export const CLIENT_ONLY = 'CLIENT_ONLY';

// AUTH
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

// HELLO

export const GET_HELLO_REQUEST = 'GET_HELLO_REQUEST';
export const GET_HELLO_SUCCESS = 'GET_HELLO_SUCCESS';
export const GET_HELLO_FAILURE = 'GET_HELLO_FAILURE';
